/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplySuccessRouteImport } from './routes/apply.success'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVisitsRouteImport } from './routes/_authenticated/admin.visits'
import { Route as AuthenticatedAdminMeetingRouteImport } from './routes/_authenticated/admin.meeting'
import { Route as AuthenticatedAdminDiagnosticRouteImport } from './routes/_authenticated/admin.diagnostic'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminDiagnosticRunRouteImport } from './routes/_authenticated/admin.diagnostic.run'
import { Route as AuthenticatedAdminDiagnosticSessionIdRouteImport } from './routes/_authenticated/admin.diagnostic.session.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySuccessRoute = ApplySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ApplyRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVisitsRoute =
  AuthenticatedAdminVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMeetingRoute =
  AuthenticatedAdminMeetingRouteImport.update({
    id: '/meeting',
    path: '/meeting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticRoute =
  AuthenticatedAdminDiagnosticRouteImport.update({
    id: '/diagnostic',
    path: '/diagnostic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDiagnosticRunRoute =
  AuthenticatedAdminDiagnosticRunRouteImport.update({
    id: '/run',
    path: '/run',
    getParentRoute: () => AuthenticatedAdminDiagnosticRoute,
  } as any)
const AuthenticatedAdminDiagnosticSessionIdRoute =
  AuthenticatedAdminDiagnosticSessionIdRouteImport.update({
    id: '/session/$id',
    path: '/session/$id',
    getParentRoute: () => AuthenticatedAdminDiagnosticRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/apply/success': typeof ApplySuccessRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/diagnostic': typeof AuthenticatedAdminDiagnosticRouteWithChildren
  '/admin/meeting': typeof AuthenticatedAdminMeetingRoute
  '/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/diagnostic/run': typeof AuthenticatedAdminDiagnosticRunRoute
  '/admin/diagnostic/session/$id': typeof AuthenticatedAdminDiagnosticSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/apply/success': typeof ApplySuccessRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/diagnostic': typeof AuthenticatedAdminDiagnosticRouteWithChildren
  '/admin/meeting': typeof AuthenticatedAdminMeetingRoute
  '/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/diagnostic/run': typeof AuthenticatedAdminDiagnosticRunRoute
  '/admin/diagnostic/session/$id': typeof AuthenticatedAdminDiagnosticSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/apply/success': typeof ApplySuccessRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/diagnostic': typeof AuthenticatedAdminDiagnosticRouteWithChildren
  '/_authenticated/admin/meeting': typeof AuthenticatedAdminMeetingRoute
  '/_authenticated/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/diagnostic/run': typeof AuthenticatedAdminDiagnosticRunRoute
  '/_authenticated/admin/diagnostic/session/$id': typeof AuthenticatedAdminDiagnosticSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/apply/success'
    | '/admin/$id'
    | '/admin/diagnostic'
    | '/admin/meeting'
    | '/admin/visits'
    | '/admin/'
    | '/admin/diagnostic/run'
    | '/admin/diagnostic/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/sitemap.xml'
    | '/apply/success'
    | '/admin/$id'
    | '/admin/diagnostic'
    | '/admin/meeting'
    | '/admin/visits'
    | '/admin'
    | '/admin/diagnostic/run'
    | '/admin/diagnostic/session/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/apply/success'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/diagnostic'
    | '/_authenticated/admin/meeting'
    | '/_authenticated/admin/visits'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/diagnostic/run'
    | '/_authenticated/admin/diagnostic/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/success': {
      id: '/apply/success'
      path: '/success'
      fullPath: '/apply/success'
      preLoaderRoute: typeof ApplySuccessRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/visits': {
      id: '/_authenticated/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AuthenticatedAdminVisitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/meeting': {
      id: '/_authenticated/admin/meeting'
      path: '/meeting'
      fullPath: '/admin/meeting'
      preLoaderRoute: typeof AuthenticatedAdminMeetingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostic': {
      id: '/_authenticated/admin/diagnostic'
      path: '/diagnostic'
      fullPath: '/admin/diagnostic'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostic/run': {
      id: '/_authenticated/admin/diagnostic/run'
      path: '/run'
      fullPath: '/admin/diagnostic/run'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticRunRouteImport
      parentRoute: typeof AuthenticatedAdminDiagnosticRoute
    }
    '/_authenticated/admin/diagnostic/session/$id': {
      id: '/_authenticated/admin/diagnostic/session/$id'
      path: '/session/$id'
      fullPath: '/admin/diagnostic/session/$id'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticSessionIdRouteImport
      parentRoute: typeof AuthenticatedAdminDiagnosticRoute
    }
  }
}

interface AuthenticatedAdminDiagnosticRouteChildren {
  AuthenticatedAdminDiagnosticRunRoute: typeof AuthenticatedAdminDiagnosticRunRoute
  AuthenticatedAdminDiagnosticSessionIdRoute: typeof AuthenticatedAdminDiagnosticSessionIdRoute
}

const AuthenticatedAdminDiagnosticRouteChildren: AuthenticatedAdminDiagnosticRouteChildren =
  {
    AuthenticatedAdminDiagnosticRunRoute: AuthenticatedAdminDiagnosticRunRoute,
    AuthenticatedAdminDiagnosticSessionIdRoute:
      AuthenticatedAdminDiagnosticSessionIdRoute,
  }

const AuthenticatedAdminDiagnosticRouteWithChildren =
  AuthenticatedAdminDiagnosticRoute._addFileChildren(
    AuthenticatedAdminDiagnosticRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminDiagnosticRoute: typeof AuthenticatedAdminDiagnosticRouteWithChildren
  AuthenticatedAdminMeetingRoute: typeof AuthenticatedAdminMeetingRoute
  AuthenticatedAdminVisitsRoute: typeof AuthenticatedAdminVisitsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminDiagnosticRoute:
    AuthenticatedAdminDiagnosticRouteWithChildren,
  AuthenticatedAdminMeetingRoute: AuthenticatedAdminMeetingRoute,
  AuthenticatedAdminVisitsRoute: AuthenticatedAdminVisitsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApplyRouteChildren {
  ApplySuccessRoute: typeof ApplySuccessRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplySuccessRoute: ApplySuccessRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
